PREFIX ns1: <http://vocab.ox.ac.uk/projectfunding#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX bibo: <http://purl.org/ontology/bibo/>
SELECT DISTINCT ?funding_agency_iri ?funding_agency_name  WHERE {
    VALUES ?paper {
        <http://ceur-ws.org/Vol-1123/#paper5>
        <http://ceur-ws.org/Vol-1155/#paper-04>
    } .
    ?funding_agency_iri ns1:funds ?paper .
    ?funding_agency_iri rdf:type foaf:Organization .
    ?funding_agency_iri bibo:name ?funding_agency_name .
}

