SELECT DISTINCT ?resource_iri ?grant_identifier ?grant_name WHERE {
    VALUES ?paper {
        <http://ceur-ws.org/Vol-315/#paper1>
        <http://ceur-ws.org/Vol-1302/#paper5>
    } .
    ?resource_iri arpfo:funds ?paper .
    ?resource_iri rdf:type arpfo:Grant .
    ?resource_iri bibo:name ?grant_name .
    OPTIONAL { ?resource_iri arpfo:grantNumber ?grant_identifier }
}
