SELECT DISTINCT ?resource_iri ?title ?publication_year WHERE {
    VALUES ?paper {
        <http://ceur-ws.org/Vol-1302/#paper7>
    } .
    ?paper bibo:cites ?resource_iri .
    ?resource_iri bibo:title ?title .
    ?resource_iri bibo:created ?publication_year
    OPTIONAL { ?resource_iri bibo:doi ?doi }
    FILTER (?publication_year > '2012')
}
