SELECT (STRDT(?prefix, xsd:string) AS ?prefix_str) (YEAR(?prev) AS ?p) (YEAR(?date) AS ?d) {
	{
    	SELECT ?prefix ?x (MAX(?y_date) as ?prev) {
            VALUES ?prefix {
              "Linked Data on the Web"
              "Workshop on Modular Ontologies"
              "High-Performance Computing for the Semantic Web"
            }
            ?x a bibo:Workshop ;
              rdfs:label ?x_name ;
              timeline:atDate | timeline:beginsAtDateTime ?x_date ;
              rdfs:seeAlso ?y .
            ?y a bibo:Workshop ;
              rdfs:label ?y_name ;
              timeline:atDate | timeline:beginsAtDateTime ?y_date .
      		FILTER(CONTAINS(?x_name, ?prefix) || CONTAINS(?y_name, ?prefix))
      	}
    	GROUP BY ?prefix ?x
	}
  	?x timeline:atDate | timeline:beginsAtDateTime ?date .
  	FILTER(ABS(MONTH(?date) - MONTH(?prev))>=2)
}
