SELECT ?proc ?author_name {
  VALUES ?proc {
    <http://ceur-ws.org/Vol-1085/>
    <http://ceur-ws.org/Vol-1081/>
    <http://ceur-ws.org/Vol-1014/>
    <http://ceur-ws.org/Vol-1008/>
    <http://ceur-ws.org/Vol-994/>
    <http://ceur-ws.org/Vol-937/>
    <http://ceur-ws.org/Vol-936/>
    <http://ceur-ws.org/Vol-875/>
    <http://ceur-ws.org/Vol-859/>
    <http://ceur-ws.org/Vol-846/>
    <http://ceur-ws.org/Vol-745/>
    <http://ceur-ws.org/Vol-573/>
    <http://ceur-ws.org/Vol-477/>
    <http://ceur-ws.org/Vol-353/>
    <http://ceur-ws.org/Vol-250/>
    <http://ceur-ws.org/Vol-81/>
    <http://ceur-ws.org/Vol-53/>
    <http://ceur-ws.org/Vol-33/>
    <http://ceur-ws.org/Vol-22/>
    <http://ceur-ws.org/Vol-1/>
  }
  ?proc dcterms:hasPart ?pub .
  ?pub a swc:InvitedPaper .
  ?author foaf:made ?pub ;
          foaf:name ?author_name .
}
