SELECT DISTINCT ?proc ?creator_name WHERE {
    VALUES ?proc {
        <http://ceur-ws.org/Vol-1085/>
        <http://ceur-ws.org/Vol-994/>
    } .
    ?pub dcterms:partOf ?proc ;
         dc:creator ?creator .
    ?creator foaf:name ?creator_name .
}
