SELECT ?proc ?editor_name WHERE {
    VALUES ?proc {
        <http://ceur-ws.org/Vol-1085/>
        <http://ceur-ws.org/Vol-1010/>
        <http://ceur-ws.org/Vol-1008/>
        <http://ceur-ws.org/Vol-981/>
        <http://ceur-ws.org/Vol-906/>
        <http://ceur-ws.org/Vol-859/>
        <http://ceur-ws.org/Vol-784/>
        <http://ceur-ws.org/Vol-540/>
        <http://ceur-ws.org/Vol-369/>
        <http://ceur-ws.org/Vol-232/>
        <http://ceur-ws.org/Vol-225/>
        <http://ceur-ws.org/Vol-44/>
        <http://ceur-ws.org/Vol-11/>
        <http://ceur-ws.org/Vol-1/>
    }
    ?proc   swrc:editor ?editor .
    ?editor foaf:name   ?editor_name .
}
