SELECT DISTINCT ?paper_iri ?title {
    VALUES ?workshop {
        <http://ceur-ws.org/Vol-315/>
    }

    ?paper_iri dcterms:partOf ?workshop .
    ?author_iri foaf:made ?paper_iri .
    ?paper_iri dc:title ?title .
    ?author_iri swrc:affiliation ?org_iri .
    ?org_iri dbpedia-owl:country ?country_iri .
    ?country_iri foaf:name ?country_name .
    FILTER (?country_name='Germany')

    }
