SELECT DISTINCT ?project_iri ?project_name  WHERE {
    VALUES ?paper {
        <http://ceur-ws.org/Vol-1123/#paper4>
        <http://ceur-ws.org/Vol-1123/#paper5>
    } .
    ?project_iri arpfo:funds ?paper .
    ?project_iri rdf:type arpfo:Project .
    ?project_iri bibo:name ?project_name .
}